CURRENT_DIR: "/home/yangyu/huazhuangpin/Bert_Cls_Benchmark/"
TRAIN_DIR: "data/train.txt"
EVAL_DIR: "data/eval.txt"
TEST_DIR: "data/test.txt"

bert_model_path: "huggingface_pretrained_model/bert-base-chinese"

checkpoint_path: /home/yangyu/huazhuangpin/Bert_Cls_Benchmark/checkpoint

use_cuda: True

LR: 0.00003
EPOCH: 30
batch_size: 64

categories:
  - 是
  - 否