CURRENT_DIR: "/Users/yangyu/Desktop/sogou/新词发现/bert_benchmark/"
TRAIN_DIR: "data/train/train.txt"
EVAL_DIR: "data/eval/eval.txt"
TEST_DIR: "data/test/test.txt"

bert_model_path: "huggingface_pretrained_model/bert-base-chinese"

use_cuda: True

LR: 0.00003
EPOCH: 30
batch_size: 64